# Generated by Django 4.0.8 on 2025-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='add_image_video',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
