# Generated by Django 4.0.8 on 2025-03-15 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsandevents_add_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='add_image_video',
            field=models.FileField(blank=True, help_text='Valid formats: png, jpg, jpeg, mp4, mkv, wmv, 3gp, f4v, avi, mp3', upload_to='core_media/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
    ]
