# Generated by Django 4.0.8 on 2025-03-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newsandevents_add_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
