# Generated by Django 4.0.8 on 2025-03-15 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsandevents_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='add_image_video',
            field=models.FileField(help_text='Valid formats: png, jpg, jpeg, mp4, mkv, wmv, 3gp, f4v, avi', null=True, upload_to='news_events/media/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi'])]),
        ),
    ]
