# Generated by Django 4.0.8 on 2025-03-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_newsandevents_add_image_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevents',
            name='slug',
        ),
    ]
