# Generated by Django 4.0.8 on 2025-03-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.IntegerField(choices=[('Learning', 'Learning'), ('Quiz', 'Quiz'), ('Test', 'Test')], default=0),
        ),
    ]
