# Generated by Django 4.0.8 on 2025-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0002_emailactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='phishing_attachments/'),
        ),
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='redirect_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
