# Generated by Django 4.0.8 on 2025-04-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0003_phishingemailtemplate_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='redirect_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhishingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishingtool.emailactivity')),
            ],
        ),
        migrations.AlterField(
            model_name='phishingemailtemplate',
            name='redirect_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phishingtool.redirectpage'),
        ),
    ]
