# Generated by Django 4.0.8 on 2025-04-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0004_redirectpage_phishingemailtemplate_redirect_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phishingemailtemplate',
            name='redirect_html',
        ),
    ]
