# Generated by Django 4.0.8 on 2025-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0006_emailactivity_attachment_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='sender_email',
            field=models.EmailField(default='noreply@yourdomain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='phishingemailtemplate',
            name='sender_name',
            field=models.CharField(default='Security Team', max_length=255),
        ),
    ]
