# Generated by Django 4.0.8 on 2025-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0007_phishingemailtemplate_sender_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemailtemplate',
            name='sender_email',
            field=models.EmailField(default='past.bn@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='phishingemailtemplate',
            name='sender_name',
            field=models.CharField(default='PAST', max_length=255),
        ),
    ]
