# Generated by Django 4.0.8 on 2025-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0008_alter_phishingemailtemplate_sender_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phishingemailtemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
