# Generated by Django 4.0.8 on 2025-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingtool', '0009_alter_phishingemailtemplate_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectpage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='redirect_files/'),
        ),
    ]
